1. Type of operating system you are using to produce this error:

Windows



2. Version of the Java system you are using (java -version).

12.0.2



3. Subdirectory of your Git working directory to use as the current
   directory when compiling and running your program.
proj0 



4. EXACT sequence of commands that will cause the error you are seeing,
   including anything needed to compile and execute the program.
   It is NOT acceptable to say "any execution of the program fails"; give
   us a specific one.

running test 1 and 2 from PuzzleGeneratorTests, i.e.: 
@Test
    public void puzzleTest() {
        PuzzleGenerator puzzler = new PuzzleGenerator(314159);
        Model model;
        model = puzzler.getPuzzle(5, 5, false);
        checkPuzzle(model.solution(), 5, 5, false);
        model = puzzler.getPuzzle(4, 6, false);
        checkPuzzle(model.solution(), 4, 6, false);
        model = puzzler.getPuzzle(5, 5, true);
        checkPuzzle(model.solution(), 5, 5, true);
    }

    @Test
    public void uniquePuzzleTest() {
        PuzzleGenerator puzzler = new PuzzleGenerator(314159);
        Model model;
        model = puzzler.getPuzzle(1, 2, false);
        checkPuzzle(model.solution(), 1, 2, false);
        model = puzzler.getPuzzle(1, 3, false);
        checkPuzzle(model.solution(), 1, 3, false);
    }


5. What you see when you execute the commands in 4.
"C:\Program Files\Java\jdk-12.0.2\bin\java.exe" -ea -Didea.test.cyclic.buffer.size=1048576 "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.1\lib\idea_rt.jar=59851:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.1\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.1\lib\idea_rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.1\plugins\junit\lib\junit-rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.1\plugins\junit\lib\junit5-rt.jar;C:\Users\Varun Jadia\repo\proj0\out\production\proj0;C:\Users\Varun Jadia\AppData\Local\Programs\Python\Python37-32\DLLs;C:\Users\Varun Jadia\AppData\Local\Programs\Python\Python37-32\Lib;C:\Users\Varun Jadia\AppData\Local\Programs\Python\Python37-32;C:\Users\Varun Jadia\AppData\Local\Programs\Python\Python37-32\Lib\site-packages;C:\Users\Varun Jadia\.IdeaIC2019.2\system\python_stubs\-1302352441;C:\Users\Varun Jadia\.IdeaIC2019.2\config\plugins\python-ce\helpers\python-skeletons;C:\Users\Varun Jadia\.IdeaIC2019.2\config\plugins\python-ce\helpers\typeshed\stdlib\3;C:\Users\Varun Jadia\.IdeaIC2019.2\config\plugins\python-ce\helpers\typeshed\stdlib\2and3;C:\Users\Varun Jadia\.IdeaIC2019.2\config\plugins\python-ce\helpers\typeshed\third_party\3;C:\Users\Varun Jadia\.IdeaIC2019.2\config\plugins\python-ce\helpers\typeshed\third_party\2and3;C:\Users\Varun Jadia\cs61b-software\lib\gjdb.jar;C:\Users\Varun Jadia\cs61b-software\lib\tools.jar;C:\Users\Varun Jadia\cs61b-software\lib\jpt.jar;C:\Users\Varun Jadia\cs61b-software\lib\hamcrest-core-1.3.jar;C:\Users\Varun Jadia\cs61b-software\lib\ucb-checkstyle.jar;C:\Users\Varun Jadia\cs61b-software\lib\junit-4.12.jar;C:\Users\Varun Jadia\cs61b-software\lib\ucb-f2007.jar;C:\Users\Varun Jadia\cs61b-software\lib\ucb.jar" com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 -junit4 signpost.PuzzleGeneratorTests




java.lang.IllegalArgumentException: no solution found

	at signpost.Utils.badArgs(Utils.java:28)
	at signpost.PuzzleGenerator.makeSolutionUnique(PuzzleGenerator.java:260)
	at signpost.PuzzleGenerator.getPuzzle(PuzzleGenerator.java:25)
	at signpost.PuzzleGeneratorTests.puzzleTest(PuzzleGeneratorTests.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)






java.lang.IllegalArgumentException: no solution found

	at signpost.Utils.badArgs(Utils.java:28)
	at signpost.PuzzleGenerator.makeSolutionUnique(PuzzleGenerator.java:260)
	at signpost.PuzzleGenerator.getPuzzle(PuzzleGenerator.java:25)
	at signpost.PuzzleGeneratorTests.uniquePuzzleTest(PuzzleGeneratorTests.java:64)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)



Process finished with exit code -1
